### ISSUE TITLE
Error: must bypass byte-per-second

### ISSUE THREAD

**Issue by notsooneko** [Yonle/openradio#2]
This error can happend when you aren't provide any byte-per-second argument in `player.play` function.

**Comment by Yonle** [comment]
Probably related with [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) issue that returns `bit_rate` as `N/A`.

**Comment by Yonle** [comment]
This bugs will patched in next version as well.
