### ISSUE TITLE
problems when Playing .m4a files 

### ISSUE THREAD

**Issue by DLC01** [Yonle/openradio#4]
when trying to play an .m4a file in the queue it skips it and moves onto the next song

**Comment by Yonle** [comment]
This issue marked as **Unknow**, As it's:

1. Not confirmed by other users yet
2. Other users (Including me) still able to play m4a files correctly

**Comment by Yonle** [comment]
Hey @DLC01.

Can you play another m4a files as well?

**Comment by DLC01** [comment]
I cannot play another m4a files and it's same problem it just skips it

**Comment by Yonle** [comment]
Can you execute this command:

```bash
ffmpeg -i m4a-files.m4a -analyzeduration 0 -loglevel 0 -f mp3 -map 0:a -map_metadata -1 - | mpv -
```

**Comment by Yonle** [comment]
This bug is happend when m4a files has Metadata. I'm working on it to fix it.

**Comment by Yonle** [comment]
This bug isn't happend with openradio, This bug is related with prism-media as well.

**Comment by Yonle** [comment]
## Todo
1. Remove `prism-media` support

**Comment by Yonle** [comment]
1. This issue is not a problem with `prism-media`, But a problem with `ffmpeg`.

**Comment by Yonle** [comment]
2. This isn't `ffmpeg` issue

**Comment by Yonle** [comment]
@DLC01 It seems like you're trying to play a partial files. Unfortunately, This seems impossible to do that in piping way so no idea. We're sorry about that.

**Comment by Yonle** [comment]
Your issue is related to this:
https://github.com/rosenbjerg/FFMpegCore/issues/154

**Comment by Yonle** [comment]
This new update should fix the problem yet.
