### ISSUE TITLE
Support for binding to an IP address?

### ISSUE THREAD

**Issue by trentwiles** [Yonle/openradio#5]
Could you add support for binding to an IP address? On a VPS you can't access localhost.

**Comment by Yonle** [comment]
I see this Feature request is related to Openradio CLI. The future update will including this feature as well.

**Comment by Yonle** [comment]
The only fact is that OpenRadio CLI is Listening on 0.0.0.0

**Comment by trentwiles** [comment]
Maybe you could make an option to change 0.0.0.0 to a custom ip

**Comment by Yonle** [comment]
@RiversideRocks I'm Planning about it.

**Comment by Yonle** [comment]
Job done! To listen to different address, Simply do `openradio 3000 . -a 127.0.0.3`!

Have a nice day!

**Comment by trentwiles** [comment]
Nice!
